---
- hosts: linecards
  become: yes
  tasks:
  roles:
    - global_common
    - linecard_common
    - network_netq
  handlers:
    - include: handlers/main.yml

- hosts: fabriccards
  become: yes
  roles:
    - global_common
    - fabriccard_common
    - network_netq
  handlers:
    - include: handlers/main.yml
