---
- name: Check if route map is applied
  shell: vtysh -c "show run" | grep prepend | wc -l
  register: prepend_count

- name: Apply maintenance route map
  command: net add bgp neighbor FABRIC route-map MAINTENANCE_MODE out
  when: prepend_count.stdout | int < 3

- name: Commit the change
  command: net commit
  when: prepend_count.stdout | int < 3

- name: Verify current version
  command: cat /etc/lsb-release
  register: old_release

- name: Print Current Version
  debug: 
    msg: "{{ old_release.stdout }}"

- name: Verify traffic is drained. This will take a moment...
  interface_stats:

- name: Run Apt Update 
  command: apt-get -y update

# Command module used to avoid installing Aptitude package, which Ansible relies on
- name: Run Apt Upgrade
  command: apt-get -y upgrade

- name: Reboot!
  shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for leaf to restore. Please stand by...
  wait_for: >
    host="{{ inventory_hostname }}"
    port="{{ ansible_port }}"
    delay=30
    timeout=180
  delegate_to: localhost
  become: false

- name: Verify upgraded version
  command: cat /etc/lsb-release
  register: new_release

- name: Print Upgraded Version
  debug: 
    msg: "{{ new_release.stdout }}"

# This is mainly to let netd start
- name: Give services time to start 
  pause: 
    seconds: 30

- name: load vars
  include_vars: group_vars/all

- name: Remove routemap
  command: net del bgp neighbor FABRIC route-map MAINTENANCE_MODE out

- name: Commit the change
  command: net commit

- name: Check that fabric BGP is established
  any_errors_fatal: true
  check_fabric:
