---
- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr
